name: Release Build

on:
  workflow_dispatch:
  push:
    tags: ['v*']

jobs:
  # Create Documentation PDF
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        shell: bash
        run: |
          VERSION=$(sed -n 's/^version = "\(.*\)"/\1/p' Cargo.toml | head -n1)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      
      - name: Generate User Manual
        uses: docker://asciidoctor/docker-asciidoctor
        with:
          args: asciidoctor-pdf -a icons=font doc/user_manual.adoc -o doc/summarizer-${{ env.VERSION }}-user-manual.pdf

      - name: Generate Development Manual
        uses: docker://asciidoctor/docker-asciidoctor
        with:
          args: asciidoctor-pdf -a icons=font doc/development_manual.adoc -o doc/summarizer-${{ env.VERSION }}-development-manual.pdf

      - uses: actions/upload-artifact@v4
        with:
          name: summarizer-${{ env.VERSION }}-documentation
          path: |
            doc/summarizer-${{ env.VERSION }}-user-manual.pdf
            doc/summarizer-${{ env.VERSION }}-development-manual.pdf

  # Build Binaries only
  dist:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            bin: summarizer
            triplet: x86_64-linux
          - os: windows-latest
            bin: summarizer.exe
            triplet: x86_64-windows
          - os: macos-latest
            bin: summarizer
            triplet: x86_64-macos

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Environment
        shell: bash
        run: |
          VERSION=$(sed -n 's/^version = "\(.*\)"/\1/p' Cargo.toml | head -n1)
          echo "DIR=summarizer-$VERSION-${{ matrix.triplet }}" >> $GITHUB_ENV

      - name: Build
        run: cargo build --release

      - name: Package Binary
        shell: bash
        run: |
          mkdir -p ${{ env.DIR }}/bin
          cp target/release/${{ matrix.bin }} ${{ env.DIR }}/bin/

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.DIR }}
          path: ${{ env.DIR }}/